version: "3.7"
services:
  jobmanager:
    image: flink:1.17.0-scala_2.12
    volumes:
      - ./input-raw:/input-raw
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        cluster.evenly-spread-out-slots: true
        rest.flamegraph.enabled: true
    networks:
      - test

  taskmanager:
    image: flink:1.17.0-scala_2.12
    volumes:
      - ./input-raw:/input-raw
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 3
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 6
    networks:
      - test

networks:
  test:
    external: false